make sonarcube work

diff --git a/.github/workflows/cmake-single-platform.yml b/.github/workflows/cmake-single-platform.yml
--- a/.github/workflows/cmake-single-platform.yml
+++ b/.github/workflows/cmake-single-platform.yml
@@ -28,7 +28,7 @@ jobs:
       uses: actions/cache@v4
       id: cache-gtest
       with:
-        path: "~/gtest"
+        path: "$HOME/gtest"
         key: gtest_latest
 
     - name: Install gtest
@@ -36,9 +36,9 @@ jobs:
         CACHE_HIT: ${{steps.cache-gtest.outputs.cache-hit}}
       run: |
         if [[ "$CACHE_HIT" == 'true' ]]; then
-          cd ~/gtest
+          cd $HOME/gtest
           sudo cp lib/*.a /usr/lib
-          sudo cp -R ~/gtest/* /usr
+          sudo cp -R $HOME/gtest/* /usr
         else
           git clone https://github.com/google/googletest.git
           cd googletest
@@ -46,18 +46,18 @@ jobs:
           cd build
           cmake ..
           cmake --build .
-          [ ! -d ~/gtest ] && mkdir ~/gtest
-          cmake --install . --prefix ~/gtest
-          cd ~/gtest
+          [ ! -d $HOME/gtest ] && mkdir $HOME/gtest
+          cmake --install . --prefix $HOME/gtest
+          cd $HOME/gtest
           sudo cp lib/*.a /usr/lib
-          sudo cp -R ~/gtest/* /usr
+          sudo cp -R $HOME/gtest/* /usr
         fi
 
     - name: Cache boost
       uses: actions/cache@v4
       id: cache-boost
       with:
-        path: "~/boost"
+        path: "$HOME/boost"
         key: boost_1.90.0
 
     - name: Install Boost
@@ -65,21 +65,19 @@ jobs:
         CACHE_HIT: ${{steps.cache-boost.outputs.cache-hit}}
       run: |
         if [[ "$CACHE_HIT" == 'true' ]]; then
-          sudo cp --force --recursive ~/boost/* /usr
+          sudo cp --force --recursive $HOME/boost/* /usr
         else
           BOOST_MAJOR=1
           BOOST_MID=90
           BOOST_MINOR=0
           BOOST_VER=${BOOST_MAJOR}_${BOOST_MID}_${BOOST_MINOR}
           BOOST_VER_DOT=${BOOST_MAJOR}.${BOOST_MID}.${BOOST_MINOR}
-          wget -O boost_${BOOST_VER}.tar.gz https://sourceforge.net/projects/boost/files/boost/${BOOST_VER_DOT}/boost_${BOOST_VER}.tar.gz/download
-          tar -xvf boost_${BOOST_VER}.tar.gz
+          wget --quiet -O boost_${BOOST_VER}.tar.gz https://sourceforge.net/projects/boost/files/boost/${BOOST_VER_DOT}/boost_${BOOST_VER}.tar.gz/download
+          tar -xf boost_${BOOST_VER}.tar.gz
           cd boost_${BOOST_VER}
-          ./bootstrap.sh --prefix=/home/runner/boost -j $(nproc)
-          ./b2 install -j $(nproc)
-          ./b2
-          ./b2 install
-          sudo cp --force --recursive ~/boost/* /usr
+          ./bootstrap.sh --prefix=$HOME/boost
+          ./b2 install -j $(nproc) --quiet || { echo "Boost build failed"; exit 1; }
+          sudo cp --force --recursive $HOME/boost/* /usr
         fi
 
 
